name: CDKTF Deploy

on:
  push:
    branches:
      - add-custombackend-and-cicdpreview

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16'

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get
        working-directory: ./examples/custombackend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        with:
          terraformVersion: 1.3.0
          cdktfVersion: 0.12.2
          workingDirectory: ./examples/custombackend
          mode: auto-approve-apply
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commentOnPr: false
